name: Github Actions Configuration
on: [push,workflow_dispatch]
jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Download
        uses: actions/checkout@v3
      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm test
  deployment:
    needs: configuration
    runs-on: ubuntu-20.04
    steps:
      - name: Get Code Download
        uses: actions/checkout@v3
      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm test
      - name: build project
        run: npm run build
      - name: deploy-to-host
        run: echo 'deploying....'