name: Github Actions Configuration
on: push
jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Download
        uses: actions/checkout@v3
      - name: Install Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm test